title: "Record-EsC"
description: "記録"
baseurl: "/record-Esc" # サブディレクトリ名
url: "https://shiro-tom.github.io" # GitHub Pages URL

# 投稿のURL構造
permalink: /:categories/:title/

# Markdown変換エンジン
markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: true


# プラグイン（最低限）
plugins:
  - jekyll-feed
  - jekyll-sitemap

theme: null
