title: "Shiraishi Record"
description: "雨の降った日を、雨の降った日として記憶するため"
baseurl: "/record-Esc" # サブディレクトリ名（例: /blog）不要なら空
url: "https://shiro-tom.github.io" # あなたのGitHub Pages URL

# 投稿のURL構造
permalink: /:categories/:title/

# Markdown変換エンジン
markdown: kramdown

# プラグイン（最低限）
plugins:
  - jekyll-feed
  - jekyll-sitemap

theme: null